/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace RedPacket {
  export type PacketStruct = {
    sender: AddressLike;
    token: AddressLike;
    totalAmount: BigNumberish;
    remainingAmount: BigNumberish;
    totalCount: BigNumberish;
    remainingCount: BigNumberish;
    deadline: BigNumberish;
    packetType: BigNumberish;
    message: string;
    refunded: boolean;
    exists: boolean;
  };

  export type PacketStructOutput = [
    sender: string,
    token: string,
    totalAmount: bigint,
    remainingAmount: bigint,
    totalCount: bigint,
    remainingCount: bigint,
    deadline: bigint,
    packetType: bigint,
    message: string,
    refunded: boolean,
    exists: boolean
  ] & {
    sender: string;
    token: string;
    totalAmount: bigint;
    remainingAmount: bigint;
    totalCount: bigint;
    remainingCount: bigint;
    deadline: bigint;
    packetType: bigint;
    message: string;
    refunded: boolean;
    exists: boolean;
  };

  export type ClaimedPacketViewStruct = {
    codeHash: BytesLike;
    packetId: BigNumberish;
    amount: BigNumberish;
    sender: AddressLike;
    token: AddressLike;
    message: string;
    claimedAt: BigNumberish;
  };

  export type ClaimedPacketViewStructOutput = [
    codeHash: string,
    packetId: bigint,
    amount: bigint,
    sender: string,
    token: string,
    message: string,
    claimedAt: bigint
  ] & {
    codeHash: string;
    packetId: bigint;
    amount: bigint;
    sender: string;
    token: string;
    message: string;
    claimedAt: bigint;
  };
}

export interface RedPacketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PACKET_TYPE_EQUAL"
      | "PACKET_TYPE_RANDOM"
      | "claim"
      | "claimInfoByPacketAndUser"
      | "codeHashByPacketId"
      | "createRedPacket"
      | "getAnyOneBalance"
      | "getClaimStatusByCodeHash"
      | "getPacketByCodeHash"
      | "getUserClaimHistory"
      | "getUserClaimHistoryPage"
      | "nextPacketId"
      | "packetIdByCodeHash"
      | "packets"
      | "refund"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PacketClaimed" | "PacketCreated" | "PacketRefunded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PACKET_TYPE_EQUAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PACKET_TYPE_RANDOM",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "claimInfoByPacketAndUser",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "codeHashByPacketId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createRedPacket",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAnyOneBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimStatusByCodeHash",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPacketByCodeHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserClaimHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserClaimHistoryPage",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPacketId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "packetIdByCodeHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "packets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "PACKET_TYPE_EQUAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PACKET_TYPE_RANDOM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimInfoByPacketAndUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "codeHashByPacketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRedPacket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAnyOneBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimStatusByCodeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPacketByCodeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserClaimHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserClaimHistoryPage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextPacketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "packetIdByCodeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "packets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
}

export namespace PacketClaimedEvent {
  export type InputTuple = [
    packetId: BigNumberish,
    claimer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [packetId: bigint, claimer: string, amount: bigint];
  export interface OutputObject {
    packetId: bigint;
    claimer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PacketCreatedEvent {
  export type InputTuple = [
    packetId: BigNumberish,
    sender: AddressLike,
    token: AddressLike,
    totalAmount: BigNumberish,
    count: BigNumberish,
    deadline: BigNumberish,
    packetType: BigNumberish,
    codeHash: BytesLike
  ];
  export type OutputTuple = [
    packetId: bigint,
    sender: string,
    token: string,
    totalAmount: bigint,
    count: bigint,
    deadline: bigint,
    packetType: bigint,
    codeHash: string
  ];
  export interface OutputObject {
    packetId: bigint;
    sender: string;
    token: string;
    totalAmount: bigint;
    count: bigint;
    deadline: bigint;
    packetType: bigint;
    codeHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PacketRefundedEvent {
  export type InputTuple = [
    packetId: BigNumberish,
    sender: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [packetId: bigint, sender: string, amount: bigint];
  export interface OutputObject {
    packetId: bigint;
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RedPacket extends BaseContract {
  connect(runner?: ContractRunner | null): RedPacket;
  waitForDeployment(): Promise<this>;

  interface: RedPacketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PACKET_TYPE_EQUAL: TypedContractMethod<[], [bigint], "view">;

  PACKET_TYPE_RANDOM: TypedContractMethod<[], [bigint], "view">;

  claim: TypedContractMethod<[codeHash: BytesLike], [bigint], "nonpayable">;

  claimInfoByPacketAndUser: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [boolean, bigint, bigint] & {
        claimed: boolean;
        amount: bigint;
        claimedAt: bigint;
      }
    ],
    "view"
  >;

  codeHashByPacketId: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  createRedPacket: TypedContractMethod<
    [
      token: AddressLike,
      totalAmount: BigNumberish,
      count: BigNumberish,
      packetType: BigNumberish,
      message: string
    ],
    [[bigint, string] & { packetId: bigint; codeHash: string }],
    "payable"
  >;

  getAnyOneBalance: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getClaimStatusByCodeHash: TypedContractMethod<
    [codeHash: BytesLike, user: AddressLike],
    [
      [boolean, bigint, string, string, string, bigint, bigint] & {
        hasClaimed: boolean;
        amount: bigint;
        sender: string;
        message: string;
        token: string;
        claimedAt: bigint;
        packetId: bigint;
      }
    ],
    "view"
  >;

  getPacketByCodeHash: TypedContractMethod<
    [codeHash: BytesLike],
    [
      [bigint, RedPacket.PacketStructOutput] & {
        packetId: bigint;
        packet: RedPacket.PacketStructOutput;
      }
    ],
    "view"
  >;

  getUserClaimHistory: TypedContractMethod<
    [user: AddressLike],
    [RedPacket.ClaimedPacketViewStructOutput[]],
    "view"
  >;

  getUserClaimHistoryPage: TypedContractMethod<
    [user: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [
      [RedPacket.ClaimedPacketViewStructOutput[], bigint] & {
        records: RedPacket.ClaimedPacketViewStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;

  nextPacketId: TypedContractMethod<[], [bigint], "view">;

  packetIdByCodeHash: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  packets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        sender: string;
        token: string;
        totalAmount: bigint;
        remainingAmount: bigint;
        totalCount: bigint;
        remainingCount: bigint;
        deadline: bigint;
        packetType: bigint;
        message: string;
        refunded: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  refund: TypedContractMethod<[packetId: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PACKET_TYPE_EQUAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PACKET_TYPE_RANDOM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[codeHash: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "claimInfoByPacketAndUser"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [boolean, bigint, bigint] & {
        claimed: boolean;
        amount: bigint;
        claimedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "codeHashByPacketId"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createRedPacket"
  ): TypedContractMethod<
    [
      token: AddressLike,
      totalAmount: BigNumberish,
      count: BigNumberish,
      packetType: BigNumberish,
      message: string
    ],
    [[bigint, string] & { packetId: bigint; codeHash: string }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getAnyOneBalance"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getClaimStatusByCodeHash"
  ): TypedContractMethod<
    [codeHash: BytesLike, user: AddressLike],
    [
      [boolean, bigint, string, string, string, bigint, bigint] & {
        hasClaimed: boolean;
        amount: bigint;
        sender: string;
        message: string;
        token: string;
        claimedAt: bigint;
        packetId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPacketByCodeHash"
  ): TypedContractMethod<
    [codeHash: BytesLike],
    [
      [bigint, RedPacket.PacketStructOutput] & {
        packetId: bigint;
        packet: RedPacket.PacketStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserClaimHistory"
  ): TypedContractMethod<
    [user: AddressLike],
    [RedPacket.ClaimedPacketViewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserClaimHistoryPage"
  ): TypedContractMethod<
    [user: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [
      [RedPacket.ClaimedPacketViewStructOutput[], bigint] & {
        records: RedPacket.ClaimedPacketViewStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextPacketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "packetIdByCodeHash"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "packets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        sender: string;
        token: string;
        totalAmount: bigint;
        remainingAmount: bigint;
        totalCount: bigint;
        remainingCount: bigint;
        deadline: bigint;
        packetType: bigint;
        message: string;
        refunded: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[packetId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "PacketClaimed"
  ): TypedContractEvent<
    PacketClaimedEvent.InputTuple,
    PacketClaimedEvent.OutputTuple,
    PacketClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PacketCreated"
  ): TypedContractEvent<
    PacketCreatedEvent.InputTuple,
    PacketCreatedEvent.OutputTuple,
    PacketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PacketRefunded"
  ): TypedContractEvent<
    PacketRefundedEvent.InputTuple,
    PacketRefundedEvent.OutputTuple,
    PacketRefundedEvent.OutputObject
  >;

  filters: {
    "PacketClaimed(uint256,address,uint256)": TypedContractEvent<
      PacketClaimedEvent.InputTuple,
      PacketClaimedEvent.OutputTuple,
      PacketClaimedEvent.OutputObject
    >;
    PacketClaimed: TypedContractEvent<
      PacketClaimedEvent.InputTuple,
      PacketClaimedEvent.OutputTuple,
      PacketClaimedEvent.OutputObject
    >;

    "PacketCreated(uint256,address,address,uint256,uint32,uint64,uint8,bytes32)": TypedContractEvent<
      PacketCreatedEvent.InputTuple,
      PacketCreatedEvent.OutputTuple,
      PacketCreatedEvent.OutputObject
    >;
    PacketCreated: TypedContractEvent<
      PacketCreatedEvent.InputTuple,
      PacketCreatedEvent.OutputTuple,
      PacketCreatedEvent.OutputObject
    >;

    "PacketRefunded(uint256,address,uint256)": TypedContractEvent<
      PacketRefundedEvent.InputTuple,
      PacketRefundedEvent.OutputTuple,
      PacketRefundedEvent.OutputObject
    >;
    PacketRefunded: TypedContractEvent<
      PacketRefundedEvent.InputTuple,
      PacketRefundedEvent.OutputTuple,
      PacketRefundedEvent.OutputObject
    >;
  };
}
