/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as goodsSol from "./goods.sol";
export * as redpackSol from "./redpack.sol";
export * as tokenInterface from "./token_interface";
export * as transformSol from "./transform.sol";
export { XXB__factory } from "./XXB__factory";
